### ISSUE TITLE
Screen weird after being in shiprekt server

### ISSUE THREAD

**Issue by ProfessorFumbleFingers** [Gingerbeard5773/Shiprekt#33] opened 2021-12-17 20:32 UTC
Joining into another default ctf for example the camera moves more jerky if you have played shiprekt during same kag runtime.

**Comment by Gingerbeard5773** [comment] 2022-02-25 09:30
Likely caused by setting the autoconfig variable camera_ints to a custom digit. Since it is a autocfg variable it carries out of shiprekt. Looks like it gets reset on kag restart though. This really isn't a big deal of a bug and it may not be worth fixing. Likely you'd need to store the var when the player joins and then set it back when they leave.

**Comment by Gingerbeard5773** [comment] 2022-03-26 03:00
Found out the reason. it is caused by ``float posLag``. Apparently the engine does not reset CCamera values after leaving a server, so it is kept through different servers because base-kag *does not* set the posLag anywhere. Closing

**Closed by Gingerbeard5773** 2022-03-26 03:00 UTC
Labels: bug, wontdo
