### ISSUE TITLE
Block description placements in shop more consistent

### ISSUE THREAD

**Issue by ProfessorFumbleFingers** [Gingerbeard5773/Shiprekt#23] opened 2021-12-16 21:04 UTC
They currently are all over the place when you hover over different blocks, they need uniformity.

**Comment by Gingerbeard5773** [comment] 2022-01-04 09:40
Caused by the caption dimensions being different sizes. If the captions were all the same size it would be more consistent. In the end though it's more something caused by the engine.

**Comment by Gingerbeard5773** [comment] 2022-03-01 02:57
Closing since its now >>good enough<<

**Closed by Gingerbeard5773** 2022-03-01 02:57 UTC
Labels: improvement
